export default posts = [
  {
    id: 1,
    firstName: "Javaid",
    lastName: "Khan",
    location: "Srinagar Kashmir",
    likes: 1601,
    comments: 36,
    bookmarks: 89,
  },
  {
    id: 2,
    firstName: "Sahil",
    lastName: "Khan",
    location: "Srinagar Kashmir",
    likes: 1601,
    comments: 36,
    bookmarks: 89,
  },
  {
    id: 3,
    firstName: "Suhail",
    lastName: "Khan",
    location: "Srinagar Kashmir",
    likes: 1601,
    comments: 36,
    bookmarks: 89,
  },
  {
    id: 4,
    firstName: "Aqib",
    lastName: "Khan",
    location: "Srinagar Kashmir",
    likes: 1601,
    comments: 36,
    bookmarks: 89,
  },
  {
    id: 5,
    firstName: "Hassan",
    lastName: "Khan",
    location: "Srinagar Kashmir",
    likes: 1601,
    comments: 36,
    bookmarks: 89,
  },
  {
    id: 6,
    firstName: "Iqra",
    lastName: "Khan",
    location: "Srinagar Kashmir",
    likes: 1601,
    comments: 36,
    bookmarks: 89,
  },
  {
    id: 7,
    firstName: "Ayan",
    lastName: "Khan",
    location: "Srinagar Kashmir",
    likes: 1601,
    comments: 36,
    bookmarks: 89,
  },
  {
    id: 8,
    firstName: "Riyan",
    lastName: "Khan",
    location: "Srinagar Kashmir",
    likes: 1601,
    comments: 36,
    bookmarks: 89,
  },
  {
    id: 9,
    firstName: "Zuhan",
    lastName: "Khan",
    location: "Srinagar Kashmir",
    likes: 1601,
    comments: 36,
    bookmarks: 89,
  },
];
